parameters:
    ongr_connections.import.modifier.class: ONGR\ProcessWireConnectorBundle\Modifier\ContentImportModifier
    ongr_processwire_connector.import.consumer.class: ONGR\ProcessWireConnectorBundle\Consumer\ContentImportConsumer
    ongr_processwire_connector.import.source.class: ONGR\ProcessWireConnectorBundle\Source\ContentImportSource
    ongr_processwire_connector.page_service_address: http://processwire.ongr.dev/en/service-pages/?template=basic-page
    ongr_processwire_connector.tree_parent: /
    ongr_processwire_connector.document_repository: ONGRDemoProcessWireBundle:ContentDocument
