parameters:
    ongr_demo.magento.url: http://magento.ongr.dev
    shop_ids:
        - 0

imports:
    - { resource: project_defaults.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:          { asset_reset: %asset_reset%, top_cms_links: %top_cms_links% }

# SSI config
crunch_ssi:
    inline:     false
    use_header: true

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ONGRDemoBundle, ONGRDemoMagentoBundle ]
    java: "%java_path%"
    filters:
        cssrewrite: ~
        sass: ~
        compass: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
    assets:
        demo_css:
            inputs:
                - "@ONGRDemoBundle/Resources/public/style/ongr.scss"
            filters:
                - compass
        demo_js:
            inputs:
                - "@ONGRDemoBundle/Resources/public/scripts/**/*.js"
                - "@ONGRDemoBundle/Resources/public/scripts/main.js"
            filters:
                - closure


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            ONGRMagentoConnectorBundle:
                type: annotation
                alias: MagentoConnectorBundle
                dir: Entity
                prefix: ONGR\MagentoConnectorBundle\Entity
                is_bundle: true
            ONGRDemoMagentoBundle:
                type: annotation
                alias: DemoMagentoBundle
                dir: Entity
                prefix: ONGR\DemoMagentoBundle\Entity
                is_bundle: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

ongr_content:
    es:
        repositories:
            product:  es.manager.default.product
            content:  es.manager.default.content
            category: es.manager.default.category
    category_root_id: 2

ongr_router:
    es_manager: default
    seo_routes:
        product:
            _controller: ONGRDemoBundle:Product:document
            _route: ongr_product
            _default_route: ongr_product
            _id_param: id
        category:
            _controller: ONGRDemoBundle:Category:document
            _route: ongr_category
            _default_route: ongr_category
            _id_param: id
        content:
            _route: ongr_content
            _default_route: ongr_content
            _id_param: document
            _controller: ONGRDemoBundle:Content:document

ongr_elasticsearch:
    connections:
        default:
            hosts:
                - { host: "%es_host%" }
            index_name: "%es_index_name%"
            settings:
                number_of_shards: "%es_number_of_shards%"
                number_of_replicas: "%es_number_of_replicas%"
                index:
                    refresh_interval: "%es_refresh_interval%"
                analysis:
                    tokenizer:
                        pathTokenizer:
                            type : path_hierarchy
                            buffer_size: 2024
                            skip: 0
                            delimiter: /
                    filter:
                        incremental_filter:
                            type: edge_ngram
                            min_gram: 1
                            max_gram: 20
                    analyzer:
                        indexAnalyzer:
                            type: snowball
                            language: German2
                            stopwords: "der,die,das,mit,und,für"
                        searchAnalyzer:
                            type: snowball
                            language: German2
                            stopwords: "der,die,das,mit,und,für"
                        pathAnalyzer:
                            type: custom
                            tokenizer: pathTokenizer
                        urlAnalyzer:
                            type: custom
                            tokenizer: keyword
                            filter: [lowercase]
                        incrementalAnalyzer:
                            type: custom
                            tokenizer: standard
                            filter:
                                - lowercase
                                - incremental_filter

    managers:
        default:
            connection: default
            debug: "%kernel.debug%"
            mappings:
                - ONGRDemoBundle
                - ONGRConnectionsBundle

        magento:
            connection: default
            debug: "%kernel.debug%"
            mappings:
                - ONGRDemoMagentoBundle
                - ONGRMagentoConnectorBundle

ongr_filter_manager:
    managers:
        product_list:
            filters:
                - category
                - wear_title
                - search
                - pager
                - sorting
            repository: 'product'
    filters:
        choice:
            wear_title:
                request_field: 'title'
                field: title
        match:
            search:
                request_field: 'q'
                field: title
        document_field:
            category:
                request_field: 'document'
                field: categories.categories
        pager:
            pager:
                request_field: 'page'
                count_per_page: 9
                max_pages: 10
        sort:
            sorting:
                request_field: 'sort'
                choices:
                    - { label: Price ascending, field: price, default: true }
                    - { label: Price descending, field: price, order: desc }
                    - { label: Title ascending, field: title }
                    - { label: Title descending, field: title, order: desc }

ongr_connections:
    shops:
        test: { shop_id: 0 }
    active_shop: test
    sync:
        sync_storage:
            mysql:
                connection: default
                table_name: ongr_sync_storage

ongr_magento:
    store_id: 0
    shop_id: 1
    url: http://magento.ongr.dev
    es_manager: magento
    product_repository: ONGRMagentoConnectorBundle:ProductDocument
